export const initialFormState = {
    email: { value: "", isFocussed: false },
    name: { value: "", isFocussed: false },
    age: { value: 0, isFocussed: false },
    qualification: { value: "", isFocussed: false },
    institute: { value: "", isFocussed: false },
    field: { value: "", isFocussed: false },
    experience: { value: "", isFocussed: false },
    institutecanada: { value: "", isFocussed: false },
    programcanada: { value: "", isFocussed: false },
    countryorigin: { value: "", isFocussed: false },
    goals: { value: "", isFocussed: false },
    listening: { value: "", isFocussed: false },
    reading: { value: "", isFocussed: false },
    speaking: { value: "", isFocussed: false },
    writing: { value: "", isFocussed: false },
    firsttution: { value: "no", isFocussed: false },
    tutionfees: { value: "", isFocussed: false },
    gic: { value: "no", isFocussed: false },
    gicpay: { value: "", isFocussed: false },
}